#!/bin/bash

set -u
set -e

CONFIG='./upload.conf'
source "$CONFIG"

usage()
{
    HELPDEST="$(dirname $DEST)"
    HELPDEST="$(dirname $HELPDEST)"
    echo "
upload.sh
    Upload good logos to Pocketbook mounted on $HELPDEST
Usage: upload.sh [list [<DIR>] | upload | check | help ]
    list [<DIR>]  : list good logos in current or specified folder
    upload        : upload good logos to pocketbook
    check         : list logos on pocketbook
    help          : show this text
"
}

list()
{
    find "$1" -not -path './0*/*' -not -path './2012/*' -iname "*.bmp"
}

check()
{
    echo "Content of $DEST"
    ls -AFlh "$DEST"
}

if [[ -d "$DEST" ]]
then
    echo Pocketbook detected
    OK=true
else
    echo Pocketbook not detected
    OK=false
fi

if [[ $# -gt 0 ]]
then
    case "$1" in
	"help" )
		usage
		;;
    "list" )
		if [[ $# -eq 1 ]]
		then
			list ./
		else
			list "$2"
		fi
        ;;
    "upload" )
        if $OK
        then
            NOCLOBBER="-n"
            if [[ $# -gt 1 ]] && [[ "$2" == "force" ]]
            then
                NOCLOBBER=
            fi
			echo "Screensavers to upload:"
			list ./
            list ./ | xargs -ISRC cp SRC "$DEST" $NOCLOBBER
        else
            echo "Can not upload."
            exit
        fi
        ;;
    "check" )
        if $OK
        then
            check
        else
            echo "Can not check."
        fi
        ;;
    * )
        echo "Not a command : $1"
        usage
        ;;
    esac
else
    echo "no command specified"
    usage
fi

